package vista;

import javax.swing.table.DefaultTableModel;

public class ConsDependenciaInternalFrame extends javax.swing.JInternalFrame {

    private controlador.GestorDependenciaControl dependenciaControl;
    private DefaultTableModel tabla;

    public ConsDependenciaInternalFrame() {
        initComponents();
        
        dependenciaControl=new controlador.GestorDependenciaControl(this);
        String titulosTabla[]={"Identificador Dependencia","Dependencia"};
        tabla=new DefaultTableModel(null,titulosTabla);
        consTbl.setModel(tabla);
        consultarBtn.addActionListener(dependenciaControl);
    }
    public DefaultTableModel getTableModel(){
        return tabla;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        nombreOpt = new javax.swing.JRadioButton();
        todoOpt = new javax.swing.JRadioButton();
        consultarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        consTbl = new javax.swing.JTable();
        valor = new javax.swing.JTextField();
        lbImage = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Consultar Dependencia");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(nombreOpt);
        nombreOpt.setText("Nombre");
        getContentPane().add(nombreOpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        buttonGroup1.add(todoOpt);
        todoOpt.setText("Todo");
        getContentPane().add(todoOpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        consultarBtn.setText("Consultar");
        getContentPane().add(consultarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 40, -1, -1));

        consTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(consTbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 97, 382, 170));
        getContentPane().add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 44, 120, -1));
        getContentPane().add(lbImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 110, 90));

        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 410, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JTable consTbl;
    public javax.swing.JButton consultarBtn;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JLabel lbImage;
    public javax.swing.JRadioButton nombreOpt;
    public javax.swing.JRadioButton todoOpt;
    public javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
