package vista;

import javax.swing.table.DefaultTableModel;

public class ConsTecnologoInternalFrame extends javax.swing.JInternalFrame {

    private controlador.GestorTecnologoControl gestorTecnologoControl;
    private DefaultTableModel tabla;

    public ConsTecnologoInternalFrame() {
        initComponents();
        
        gestorTecnologoControl=new controlador.GestorTecnologoControl(this);
        String titulosTabla[]={"Identificacion","Nombres","Apellidos"};
        tabla=new DefaultTableModel(null,titulosTabla);
        ResultadosTbl.setModel(tabla);
        AceptarBtn.addActionListener(gestorTecnologoControl);
    }
    
    public DefaultTableModel getTableModel(){
        return tabla;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        IdentificadorOpt = new javax.swing.JRadioButton();
        NombresOpt = new javax.swing.JRadioButton();
        ApellidosOpt = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        ValorTxt = new javax.swing.JTextField();
        AceptarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultadosTbl = new javax.swing.JTable();
        lbImage = new javax.swing.JLabel();
        todoOpt = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setClosable(true);
        setTitle("Buscar Tecnicos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(IdentificadorOpt);
        IdentificadorOpt.setText("Identificacion");
        getContentPane().add(IdentificadorOpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, -1, -1));

        buttonGroup1.add(NombresOpt);
        NombresOpt.setText("Nombres");
        getContentPane().add(NombresOpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 7, -1, -1));

        buttonGroup1.add(ApellidosOpt);
        ApellidosOpt.setText("Apellidos");
        ApellidosOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidosOptActionPerformed(evt);
            }
        });
        getContentPane().add(ApellidosOpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 7, -1, -1));

        jLabel1.setText("Valor a buscar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 41, -1, -1));
        getContentPane().add(ValorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 198, -1));

        AceptarBtn.setText("Aceptar");
        AceptarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AceptarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 37, -1, -1));

        ResultadosTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ResultadosTbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, 510, 240));
        getContentPane().add(lbImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 90, 70));

        buttonGroup1.add(todoOpt);
        todoOpt.setText("Todos");
        getContentPane().add(todoOpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 7, -1, -1));

        jTextField2.setBorder(null);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -10, 540, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ApellidosOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidosOptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidosOptActionPerformed

    private void AceptarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AceptarBtnActionPerformed

        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AceptarBtn;
    public javax.swing.JRadioButton ApellidosOpt;
    public javax.swing.JRadioButton IdentificadorOpt;
    public javax.swing.JRadioButton NombresOpt;
    public javax.swing.JTable ResultadosTbl;
    public javax.swing.JTextField ValorTxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JLabel lbImage;
    public javax.swing.JRadioButton todoOpt;
    // End of variables declaration//GEN-END:variables

    
}
