/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Soporte 2
 */
public class ElimSoporteInternalFrame extends javax.swing.JInternalFrame {

    private controlador.EliminarSoporteControl eliminarSoporteControl;
    private DefaultTableModel tab;
    public ElimSoporteInternalFrame() {
        initComponents();
        eliminarSoporteControl=new controlador.EliminarSoporteControl(this);
        String titulos[]={"Identificacion","Nombre Usuario","Descripcion Soporte","Fecha Del Soporte"};
        tab=new DefaultTableModel(null,titulos);
        elimTbl.setModel(tab);
        elimSop.addActionListener(eliminarSoporteControl);
    }
    public DefaultTableModel getTableModel(){
        return tab;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        elimSop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        elimTbl = new javax.swing.JTable();
        lbImage = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Eliminar Soporte");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 272, 182, -1));

        jLabel2.setText("Identificador del soporte");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 276, -1, -1));

        elimSop.setText("Eliminar");
        getContentPane().add(elimSop, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 268, 107, -1));

        elimTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(elimTbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 84, 475, 178));
        getContentPane().add(lbImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 120, 80));

        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 480, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton elimSop;
    public javax.swing.JTable elimTbl;
    public javax.swing.JTextField id;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JLabel lbImage;
    // End of variables declaration//GEN-END:variables
}
