/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Soporte 2
 */
public class ElimDependenciaInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ElimDependenciaInternalFrame
     */
    private controlador.EliminarDependenciaControl dependenciaControl;
    public ElimDependenciaInternalFrame() {
        initComponents();
        dependenciaControl=new controlador.EliminarDependenciaControl(this);
        eliminarBtn.addActionListener(dependenciaControl);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idDependencia = new javax.swing.JTextField();
        eliminarBtn = new javax.swing.JButton();
        lbImage = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Eliminar Dependencia");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Identificador de dependencia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));
        getContentPane().add(idDependencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, 164, -1));

        eliminarBtn.setText("Eliminar dependencia");
        getContentPane().add(eliminarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 58, 164, -1));
        getContentPane().add(lbImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 6, 100, 80));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -6, 320, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton eliminarBtn;
    public javax.swing.JTextField idDependencia;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JLabel lbImage;
    // End of variables declaration//GEN-END:variables
}
