/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;

/**
 *
 * @author Alejandro
 */
public class ModiTecnologoInternalFrame extends javax.swing.JInternalFrame {

    private controlador.ModificarTecnologoControl modificarPacienteControl;
    public ModiTecnologoInternalFrame() {
        initComponents();
        modificarPacienteControl=new controlador.ModificarTecnologoControl(this);
        modificarBtn.addActionListener(modificarPacienteControl);
        lbImage.setBackground(Color.white);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        identificacionOpt = new javax.swing.JRadioButton();
        nombresOpt = new javax.swing.JRadioButton();
        apellidosOpt = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        valorTxt = new javax.swing.JTextField();
        modificarBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        antiguoTxt = new javax.swing.JTextField();
        lbImage = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jLabel3.setText("jLabel3");

        setClosable(true);
        setTitle("Modificar Tecnico");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(identificacionOpt);
        identificacionOpt.setText("Identificacion");
        getContentPane().add(identificacionOpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 7, -1, -1));

        buttonGroup1.add(nombresOpt);
        nombresOpt.setText("Nombres");
        getContentPane().add(nombresOpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 7, -1, -1));

        buttonGroup1.add(apellidosOpt);
        apellidosOpt.setText("Apellidos");
        getContentPane().add(apellidosOpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 7, -1, -1));

        jLabel1.setText("Valor a modificar:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setText("Valor nuevo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, -1, -1));
        getContentPane().add(valorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 64, 169, -1));

        modificarBtn.setText("Modificar");
        getContentPane().add(modificarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 160, -1));

        jLabel4.setText("Identificacion en el sistema");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, -1, -1));
        getContentPane().add(antiguoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 32, 169, -1));

        lbImage.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 130, 110));

        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -6, 490, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField antiguoTxt;
    public javax.swing.JRadioButton apellidosOpt;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JRadioButton identificacionOpt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JLabel lbImage;
    public javax.swing.JButton modificarBtn;
    public javax.swing.JRadioButton nombresOpt;
    public javax.swing.JTextField valorTxt;
    // End of variables declaration//GEN-END:variables
}
