/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Soporte 2
 */
public class ModiDependenciaInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModiDependenciaInternalFrame
     */
    
    controlador.ModificarDependenciaControl dependenciaControl;
    public ModiDependenciaInternalFrame() {
        initComponents();
        dependenciaControl=new controlador.ModificarDependenciaControl(this);
        modificar.addActionListener(dependenciaControl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idDependencia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        lbImage = new javax.swing.JLabel();
        modificar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Modificar Dependencia");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Identificador en el sistema");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));
        getContentPane().add(idDependencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 6, 89, -1));

        jLabel2.setText("Valor nuevo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 54, -1, -1));
        getContentPane().add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 50, 89, -1));
        getContentPane().add(lbImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 9, 100, 90));

        modificar.setText("Modificar");
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 89, 89, -1));

        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -20, 440, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField idDependencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JLabel lbImage;
    public javax.swing.JButton modificar;
    public javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
