/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Soporte 2
 */
public class ModiSoporteInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModiSoporteInternalFrame
     */
    
    private controlador.ModificarSoporteControl modiSoporteControl;
    private modelo.GestorDatos gestorDatos;
    public ModiSoporteInternalFrame() {
        initComponents();
        modiSoporteControl=new controlador.ModificarSoporteControl(this);
        gestorDatos=new modelo.GestorDatos();
        gestorDatos.getDependencias(dependencia);
        gestorDatos.getTecnologos(tecnologo);
        modiBtn.addActionListener(modiSoporteControl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        dependenciaOpt = new javax.swing.JRadioButton();
        tecnologoOpt = new javax.swing.JRadioButton();
        tipoOpt = new javax.swing.JRadioButton();
        fechaOpt = new javax.swing.JRadioButton();
        usuarioOpt = new javax.swing.JRadioButton();
        usuario = new javax.swing.JTextField();
        fecha = new com.toedter.calendar.JDateChooser();
        modiBtn = new javax.swing.JButton();
        dependencia = new javax.swing.JComboBox<>();
        tecnologo = new javax.swing.JComboBox<>();
        tipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        idSoporte = new javax.swing.JTextField();
        lbImage = new javax.swing.JLabel();
        estado = new javax.swing.JComboBox<>();
        estadoOpt = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Modificar soporte");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(dependenciaOpt);
        dependenciaOpt.setText("Dependencia");
        getContentPane().add(dependenciaOpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 6, 141, -1));

        buttonGroup1.add(tecnologoOpt);
        tecnologoOpt.setText("Tecnico");
        tecnologoOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecnologoOptActionPerformed(evt);
            }
        });
        getContentPane().add(tecnologoOpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 40, 141, -1));

        buttonGroup1.add(tipoOpt);
        tipoOpt.setText("Tipo");
        getContentPane().add(tipoOpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 74, 141, -1));

        buttonGroup1.add(fechaOpt);
        fechaOpt.setText("Fecha");
        getContentPane().add(fechaOpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 108, 141, -1));

        buttonGroup1.add(usuarioOpt);
        usuarioOpt.setText("Nombre de usuario");
        getContentPane().add(usuarioOpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 143, -1, -1));

        usuario.setToolTipText("Digite el valor nuevo");
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 145, 183, -1));
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 108, 183, -1));

        modiBtn.setText("Modificar");
        getContentPane().add(modiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 210, -1));

        dependencia.setToolTipText("Modifica la dependencia si la opcion esta activada");
        getContentPane().add(dependencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 7, 183, -1));

        tecnologo.setToolTipText("Modifica el tecnologo si la opcion esta activada");
        getContentPane().add(tecnologo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 41, 183, -1));

        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presencial", "Virtual" }));
        getContentPane().add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 75, 183, -1));

        jLabel2.setText("Identificador del soporte");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        idSoporte.setToolTipText("Identificador en el sistema");
        getContentPane().add(idSoporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 139, -1));
        getContentPane().add(lbImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 90, 80));

        estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "completado", "en seguimiento" }));
        getContentPane().add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 180, -1));

        buttonGroup1.add(estadoOpt);
        estadoOpt.setText("Estado");
        getContentPane().add(estadoOpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tecnologoOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecnologoOptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tecnologoOptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> dependencia;
    public javax.swing.JRadioButton dependenciaOpt;
    public javax.swing.JComboBox<String> estado;
    public javax.swing.JRadioButton estadoOpt;
    public com.toedter.calendar.JDateChooser fecha;
    public javax.swing.JRadioButton fechaOpt;
    public javax.swing.JTextField idSoporte;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JLabel lbImage;
    public javax.swing.JButton modiBtn;
    public javax.swing.JComboBox<String> tecnologo;
    public javax.swing.JRadioButton tecnologoOpt;
    public javax.swing.JComboBox<String> tipo;
    public javax.swing.JRadioButton tipoOpt;
    public javax.swing.JTextField usuario;
    public javax.swing.JRadioButton usuarioOpt;
    // End of variables declaration//GEN-END:variables
}
