/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Soporte 2
 */
public class RegDependenciaInternalFrame extends javax.swing.JInternalFrame {

    /** Creates new form RegDependenciaInternalFrame */
    
    private controlador.DependenciaControl dependenciaControlador;
    public RegDependenciaInternalFrame() {
        initComponents();
        dependenciaControlador=new controlador.DependenciaControl(this);
        regDependencia.addActionListener(dependenciaControlador);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dependencia = new javax.swing.JTextField();
        regDependencia = new javax.swing.JButton();
        lbImage = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Registrar Dependencia");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre de la dependencia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, 163, -1));
        getContentPane().add(dependencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 32, 163, -1));

        regDependencia.setText(" Registrar dependencia");
        getContentPane().add(regDependencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 62, -1, -1));
        getContentPane().add(lbImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 140, 100));

        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 380, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField dependencia;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JLabel lbImage;
    public javax.swing.JButton regDependencia;
    // End of variables declaration//GEN-END:variables

}
