/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Soporte 2
 */
public class RegSoporteInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegSoporteInternalFrame
     */
    modelo.GestorDatos gd;
    private controlador.SoporteControl soporteControlador;
    
    
    public RegSoporteInternalFrame() {
        
        initComponents();
        
        gd=new modelo.GestorDatos();
        
        gd.getTecnologos(tecnologo);
        gd.getDependencias(dependencia);
        gd.getCorreos(ListaCor);
        correosTable.setText("");
        soporteControlador=new controlador.SoporteControl(this);
        regSoporte.addActionListener(soporteControlador);
        clearBtn.addActionListener(soporteControlador);
        agregarCorreos.addActionListener(soporteControlador);
        agregarCor.addActionListener(soporteControlador);
        cancelarCor.addActionListener(soporteControlador);
        
        SpinnerNumberModel mod = new SpinnerNumberModel();
        SpinnerNumberModel mod2 = new SpinnerNumberModel();
        mod.setMaximum(24);
        mod.setMinimum(0);
        shora.setModel(mod);
        mod2.setMaximum(59);
        mod2.setMinimum(0);
        smin.setModel(mod2);
        jInternalFrame1.setVisible(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        shora = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        smin = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        descSoporte = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        presencial = new javax.swing.JRadioButton();
        nomUsuario = new javax.swing.JTextField();
        virtual = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dependencia = new javax.swing.JComboBox<>();
        tecnologo = new javax.swing.JComboBox<>();
        regSoporte = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        lbImage = new javax.swing.JLabel();
        agregarCorreos = new javax.swing.JButton();
        correosText = new javax.swing.JTextField();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        correosTable = new javax.swing.JTextArea();
        agregarCor = new javax.swing.JButton();
        cancelarCor = new javax.swing.JButton();
        ListaCor = new javax.swing.JComboBox<>();
        correoNuevo = new javax.swing.JTextField();
        agregarBtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        estadoOpt = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Registrar Soporte");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Fecha Del Soporte");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, 29));

        shora.setToolTipText("(0-24)");
        getContentPane().add(shora, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        jLabel6.setText("h:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        jLabel5.setText("Hora");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));
        getContentPane().add(smin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        descSoporte.setColumns(20);
        descSoporte.setRows(5);
        jScrollPane1.setViewportView(descSoporte);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 198, 66));

        jLabel7.setText("m:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        jLabel8.setText("Tipo");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        jLabel3.setText("Nombre De Usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, 20));

        buttonGroup1.add(presencial);
        presencial.setText("Presencial");
        getContentPane().add(presencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        nomUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(nomUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 198, -1));

        buttonGroup1.add(virtual);
        virtual.setText("Virtual");
        getContentPane().add(virtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, -1, -1));

        jLabel9.setText("Dependencia");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 198, -1));

        jLabel10.setText("Tecnico");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel2.setText("Descripcion Soporte");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        dependencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dependenciaActionPerformed(evt);
            }
        });
        getContentPane().add(dependencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 198, -1));

        getContentPane().add(tecnologo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 198, -1));

        regSoporte.setText("Registrar soporte");
        getContentPane().add(regSoporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, -1, -1));

        clearBtn.setText("Soporte Nuevo");
        getContentPane().add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, -1, -1));
        getContentPane().add(lbImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 80));

        agregarCorreos.setText("Seleccionar correos");
        agregarCorreos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCorreosActionPerformed(evt);
            }
        });
        getContentPane().add(agregarCorreos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 160, -1));
        getContentPane().add(correosText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 160, -1));

        jInternalFrame1.setToolTipText("");
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        correosTable.setColumns(20);
        correosTable.setRows(5);
        correosTable.setEnabled(false);
        jScrollPane2.setViewportView(correosTable);

        jInternalFrame1.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 40, 520, 60));

        agregarCor.setText("Listo");
        jInternalFrame1.getContentPane().add(agregarCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        cancelarCor.setText("Cancelar");
        jInternalFrame1.getContentPane().add(cancelarCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        ListaCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaCorActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(ListaCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, 152, -1));
        jInternalFrame1.getContentPane().add(correoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 10, 139, -1));

        agregarBtn.setText("Agregar correo");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(agregarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 6, 197, -1));

        jTextField1.setBorder(null);
        jInternalFrame1.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 520, 260));

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 520, 290));

        jLabel1.setText("Estado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        estadoOpt.setText("En seguimiento");
        getContentPane().add(estadoOpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        jTextField2.setBorder(null);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 520, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomUsuarioActionPerformed

    private void dependenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dependenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dependenciaActionPerformed

    private void agregarCorreosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCorreosActionPerformed
        jInternalFrame1.setVisible(true);
        jTextField1.setEditable(false);
        
    }//GEN-LAST:event_agregarCorreosActionPerformed

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        correosTable.append(correoNuevo.getText()+";");
    }//GEN-LAST:event_agregarBtnActionPerformed

    private void ListaCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaCorActionPerformed
        correosTable.append(ListaCor.getSelectedItem().toString()+";");
    }//GEN-LAST:event_ListaCorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> ListaCor;
    private javax.swing.JButton agregarBtn;
    public javax.swing.JButton agregarCor;
    public javax.swing.JButton agregarCorreos;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JButton cancelarCor;
    public javax.swing.JButton clearBtn;
    private javax.swing.JTextField correoNuevo;
    public javax.swing.JTextArea correosTable;
    public javax.swing.JTextField correosText;
    public javax.swing.JComboBox<String> dependencia;
    public javax.swing.JTextArea descSoporte;
    public javax.swing.JCheckBox estadoOpt;
    public com.toedter.calendar.JDateChooser fecha;
    public javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JLabel lbImage;
    public javax.swing.JTextField nomUsuario;
    public javax.swing.JRadioButton presencial;
    public javax.swing.JButton regSoporte;
    public javax.swing.JSpinner shora;
    public javax.swing.JSpinner smin;
    public javax.swing.JComboBox<String> tecnologo;
    public javax.swing.JRadioButton virtual;
    // End of variables declaration//GEN-END:variables
}
