
package vista;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
public class RegTecnologoInternalFrame extends javax.swing.JInternalFrame {

    private controlador.TecnologoControl tecnologoControlador;
    public RegTecnologoInternalFrame() {
        initComponents();
        tecnologoControlador=new controlador.TecnologoControl(this);
        RegistrarBtn.addActionListener(tecnologoControlador);
        NuevoBtn.addActionListener(tecnologoControlador);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IdentificacionTxt = new javax.swing.JTextField();
        NombresTxt = new javax.swing.JTextField();
        ApellidosTxt = new javax.swing.JTextField();
        RegistrarBtn = new javax.swing.JButton();
        NuevoBtn = new javax.swing.JButton();
        lbImage = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setBorder(null);
        setClosable(true);
        setTitle("Registrar Tecnicos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Identificacion:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 23, -1, -1));

        jLabel2.setText("Nombres");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 61, -1, -1));

        jLabel3.setText("Apellidos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 96, -1, -1));

        IdentificacionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdentificacionTxtActionPerformed(evt);
            }
        });
        getContentPane().add(IdentificacionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 20, 170, -1));

        NombresTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombresTxtActionPerformed(evt);
            }
        });
        getContentPane().add(NombresTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 58, 174, -1));
        getContentPane().add(ApellidosTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 96, 174, -1));

        RegistrarBtn.setText("Registrar");
        RegistrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(RegistrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        NuevoBtn.setText("Nuevo");
        getContentPane().add(NuevoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));
        getContentPane().add(lbImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 100, 90));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 470, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdentificacionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdentificacionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdentificacionTxtActionPerformed

    private void NombresTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombresTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombresTxtActionPerformed

    private void RegistrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ApellidosTxt;
    public javax.swing.JTextField IdentificacionTxt;
    public javax.swing.JTextField NombresTxt;
    public javax.swing.JButton NuevoBtn;
    public javax.swing.JButton RegistrarBtn;
    public javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JLabel lbImage;
    // End of variables declaration//GEN-END:variables
}
